[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000

# Add build hooks for Sanity integration
[build.environment]
  NODE_VERSION = "16"
  SANITY_WEBHOOK_SECRET = "${SANITY_WEBHOOK_SECRET}"

# Functions configuration for serverless functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Add preview mode redirect
[[redirects]]
  from = "/api/preview"
  to = "/.netlify/functions/preview"
  status = 200

# Note: Individual pub site redirects are handled by the build script
# which moves the pub page to the root when TARGET_PUB_SLUG is set
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://www.google-analytics.com https://ik.imagekit.io https://cdn.sanity.io https://images.unsplash.com; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https://www.google-analytics.com https://it7wwto3.api.sanity.io; frame-src 'self' https://events-widget.liveres.co.uk;"
    # Add service worker header for PWA support
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add caching for optimised WebP images
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  SANITY_DATASET = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  SANITY_DATASET = "production"
  PREVIEW_MODE = "true"

# Add staging environment for content preview
[context.staging.environment]
  NODE_ENV = "production"
  SANITY_DATASET = "staging"
  PREVIEW_MODE = "true"

# Plugin for Netlify Build
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "lighthouse-results"
