backend:
  name: decap-cms
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
site_url: https://whpubs.netlify.app
display_url: https://whpubs.netlify.app
logo_url: /favicon-32x32.png
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    editor:
      preview: false
    access:
      create: admin
      update: admin
      delete: admin
    workflow:
      name: editorial
      label: Editorial Workflow
      steps:
        - label: Draft
          name: draft
          delete: false
        - label: In Review
          name: review
          delete: false
        - label: Ready
          name: ready
          delete: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Alt Text", name: "imageAlt", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Title", name: "authorTitle", widget: "string"}
      - {label: "CTA Title", name: "ctaTitle", widget: "string"}
      - {label: "CTA Description", name: "ctaDescription", widget: "string"}
      - {label: "CTA Button Text", name: "ctaButton", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    preview_path: "events/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Location", name: "location", widget: "string"}

  - name: "pubs"
    label: "Pubs"
    folder: "src/content/pubs"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Website URL", name: "url", widget: "string"}